# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a1956a911619e2618c8d138aca7a3cec3181af52f5020a3c4dd5b1eb02c9c9f31de007ea5595a8dac802e66657fac940266a28028efcfea7b079ef118e136e7

test:
  secret_key_base: b0bd244b2920deb579dc89ef2219ba4a8a7e1976d4883eeb1c0f7cbf69379b08a04c50274c1d8e1c45f32b7d54888af8d185aae0602c222e012d44e7869dee63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
